# Generated by Django 4.0.10 on 2023-05-14 03:22

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.get_file_path),
        ),
    ]
