# Generated by Django 4.0.10 on 2023-05-16 16:20

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.get_file_path),
        ),
    ]
