# Generated by Django 4.0.10 on 2023-05-22 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_alter_lesson_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='users_who_completed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
