# Generated by Django 4.0.10 on 2023-05-27 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0006_lesson_users_who_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='users_who_completed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
