# Generated by Django 4.0.10 on 2023-06-23 22:07

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='appendix',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.get_appendix_path),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_appendix',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
