# Generated by Django 4.0.10 on 2023-06-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_merge_20230623_2350'),
        ('lessons', '0009_lesson_appendix_lesson_title_appendix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('lessons_order', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='courses.course')),
            ],
        ),
    ]
