# Generated by Django 4.0.10 on 2023-06-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_coursecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
