# Generated by Django 4.0.10 on 2023-06-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_coursecategory'),
        ('lessons', '0011_delete_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursecategory'),
        ),
    ]
