# Generated by Django 4.0.10 on 2023-06-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_remove_comment_parent_commentreply'),
        ('lessons', '0012_lesson_category'),
    ]

    operations = [
    ]
