# Generated by Django 4.0.10 on 2024-03-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_merge_20230626_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='extern_appendix_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
