# Generated by Django 4.0.10 on 2024-03-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_lesson_extern_appendix_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='extern_video_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
