# Generated by Django 4.0.10 on 2023-04-11 13:09

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.CharField(max_length=120, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=120, verbose_name='senha')),
                ('photo', models.CharField(max_length=256, verbose_name='foto')),
                ('about', models.TextField(verbose_name='sobre mim')),
                ('role', models.ManyToManyField(to='user.role', verbose_name='cargo')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
