# Generated by Django 4.0.10 on 2023-04-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_invitation'),
        ('user', '0002_user_courses'),
    ]

    operations = [
    ]
