# Generated by Django 4.0.10 on 2023-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_0002_invitation_0002_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, verbose_name='data de nascimento'),
        ),
    ]
