# Generated by Django 4.0.10 on 2023-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_content'),
        ('user', '0003_merge_0002_invitation_0002_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_users', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='courses.course'),
        ),
    ]
