# Generated by Django 4.0.10 on 2023-05-05 22:01

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
