# Generated by Django 4.0.10 on 2023-05-08 00:27

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
