# Generated by Django 4.0.10 on 2023-05-08 19:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to=user.models.get_file_path, verbose_name='foto'),
        ),
    ]
