# Generated by Django 4.0.10 on 2023-05-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactLink',
            field=models.URLField(null=True),
        ),
    ]
