# Generated by Django 4.0.10 on 2023-05-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_favorite_courses_alter_user_courses'),
        ('user', '0008_alter_user_photo'),
    ]

    operations = [
    ]
