# Generated by Django 4.0.10 on 2023-05-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_banner'),
        ('user', '0009_merge_20230520_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lesssons_completed',
            field=models.ManyToManyField(blank=True, related_name='users_who_completed', to='lessons.lesson'),
        ),
    ]
