# Generated by Django 4.0.10 on 2023-05-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20230520_2056'),
        ('user', '0009_user_contactlink'),
    ]

    operations = [
    ]
