# Generated by Django 4.0.10 on 2023-05-26 17:19

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_0009_merge_20230520_2056_0009_user_contactlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
