# Generated by Django 4.0.10 on 2023-05-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_0009_merge_20230520_2056_0009_user_contactlink'),
        ('user', '0011_remove_user_lesssons_completed'),
    ]

    operations = [
    ]
