# Generated by Django 4.0.10 on 2023-05-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
