# Generated by Django 4.0.10 on 2023-05-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_cpf'),
        ('user', '0012_merge_20230525_2145'),
    ]

    operations = [
    ]
