# Generated by Django 4.0.10 on 2023-05-28 00:03

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_cpf_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, validators=[user.models.User.validate_age], verbose_name='data de nascimento'),
        ),
    ]
