# Generated by Django 4.0.10 on 2023-05-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_merge_0011_alter_user_cpf_0012_merge_20230525_2145'),
        ('user', '0014_alter_user_birth'),
    ]

    operations = [
    ]
