# Generated by Django 4.0.10 on 2023-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_anotation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotation',
            name='anotations',
        ),
        migrations.AddField(
            model_name='anotation',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anotation',
            name='note',
            field=models.TextField(null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='anotation',
            name='time',
            field=models.FloatField(null=True, verbose_name='Tempo'),
        ),
        migrations.AddField(
            model_name='anotation',
            name='title',
            field=models.CharField(max_length=120, null=True, verbose_name='Titulo'),
        ),
    ]
