# Generated by Django 4.0.10 on 2023-06-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_anotation_course_anotation_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotation',
            name='link',
        ),
    ]
