# Generated by Django 4.0.10 on 2024-03-10 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_user_cpf_user_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ra',
            field=models.CharField(default='00000000', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='ra'),
        ),
    ]
