# Generated by Django 4.0.10 on 2024-03-10 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ra',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='ra'),
        ),
    ]
