# Generated by Django 4.0.10 on 2023-04-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=265)),
                ('banner', models.FileField(upload_to='media/images/courses/%Y/%m/%d')),
            ],
        ),
    ]
