# Generated by Django 4.0.10 on 2023-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.CharField(default='', max_length=512),
        ),
    ]
