# Generated by Django 4.0.10 on 2023-04-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.CharField(max_length=512),
        ),
    ]
