# Generated by Django 4.0.10 on 2023-05-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_ratings_course_alter_ratings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
