# Generated by Django 4.0.10 on 2023-05-24 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_alter_ratings_course_alter_ratings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_rating'),
        ),
    ]
