# Generated by Django 4.0.10 on 2023-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_ratings_course_alter_ratings_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='commentVisibility',
            field=models.BooleanField(default=True),
        ),
    ]
