# Generated by Django 4.0.10 on 2023-06-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_ratings_comment_ratings_commentvisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nome'),
        ),
    ]
