# Generated by Django 4.0.10 on 2023-06-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_ratings_comment_ratings_commentvisibility'),
        ('courses', '0019_progresscourserelation_and_more'),
    ]

    operations = [
    ]
