# Generated by Django 4.0.10 on 2023-06-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_ratings_user_name'),
        ('courses', '0020_merge_20230623_2350'),
    ]

    operations = [
    ]
