# Generated by Django 4.0.10 on 2023-06-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories_order',
            field=models.TextField(default='[]'),
        ),
    ]
