# Generated by Django 4.0.10 on 2023-06-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_categories_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='lessons_order',
            field=models.TextField(default='[]'),
        ),
    ]
