# Generated by Django 4.0.10 on 2023-06-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_merge_0019_ratings_user_name_0020_merge_20230623_2350'),
        ('courses', '0023_alter_coursecategory_lessons_order'),
    ]

    operations = [
    ]
